import streamlit as st
from modules.analyzer import Analyzer
from modules.auxillary import questions, answers

anal = Analyzer()
def click_handler(text, graphConfig):
    if len(text) < 50:
        st.warning('Input must be atleast 50 characters long', icon="⚠️")
    else: st.pyplot(anal.analyze(text, graphConfig))

def home():
    with st.sidebar:
        st.title("Graph settings")
        color = st.color_picker("Bar color", '#1F75FE')
        labelColor = st.color_picker("Axis label color", '#000000')
        borderColor = st.color_picker("Plot border color", '#000000')
        faceColor = st.color_picker("Plot background color", '#f0f8ff')
        backColor = st.color_picker("Graph background color", '#ffffff')
        axes = st.checkbox("Show axis names")
        horizontal_graph = st.checkbox("Horizontal Graph")

    st.title("Sentiment Analyzer")
    for i in range(len(questions)):
        input = st.text_area(questions[i], value = answers[i], max_chars = 500)
        st.caption("Default answer generated by ChatGPT<br/>OpenAI (2023) https://chat.openai.com", unsafe_allow_html = True)
        if st.button('Analyze', key = f'button{i}'): click_handler(input, {
            'graphColor': color,
            'isHorizontal': horizontal_graph,
            'showAxes': axes,
            'background': backColor,
            'faceColor': faceColor,
            'labelColor': labelColor,
            "borderColor": borderColor
        })