import streamlit as st
from streamlit_option_menu import option_menu as menu
from modules.analyzer import Analyzer
from modules.about import about
from modules.auxillary import questions, answers, load_css

anal = Analyzer()
st.set_page_config(
    page_title = 'Synthesized Infinity',
    layout = 'centered',
    initial_sidebar_state = 'collapsed'
)

# TODO: load css styles
load_css()

def click_handler(text, graphConfig):
    if len(text) < 50:
        st.warning('Input must be atleast 50 characters long', icon="⚠️")
    else: st.pyplot(anal.analyze(text, graphConfig))

with st.sidebar:
    selected = menu(
        menu_title = None,
        options = ["Home", "About"],
        icons = ["house-door-fill", "info-square-fill"]
    )
    if selected == "Home":
        st.title("Graph settings")
        color = st.color_picker("Bar color", '#1F75FE')
        labelColor = st.color_picker("Axis label color", '#000000')
        borderColor = st.color_picker("Plot border color", '#000000')
        faceColor = st.color_picker("Plot background color", '#f0f8ff')
        backColor = st.color_picker("Graph background color", '#ffffff')
        axes = st.checkbox("Show axis names")
        horizontal_graph = st.checkbox("Horizontal Graph")

if selected == "Home":
    st.title("Sentiment Analyzer")
    for i in range(len(questions)):
        input = st.text_area(questions[i], value = answers[i], max_chars = 500)
        st.caption("Default answer generated by ChatGPT<br/>OpenAI (2023) https://chat.openai.com", unsafe_allow_html = True)
        if st.button('Analyze', key = f'button{i}'): click_handler(input, {
            'graphColor': color,
            'isHorizontal': horizontal_graph,
            'showAxes': axes,
            'background': backColor,
            'faceColor': faceColor,
            'labelColor': labelColor,
            "borderColor": borderColor
        })

if selected == "About": about()